# Generated by Django 5.0.6 on 2025-01-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='todolistmodel',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='todos', to='t_list.hashtag'),
        ),
    ]
