# Generated by Django 5.0.6 on 2025-01-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_list', '0002_hashtag_todolistmodel_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
